version: "2"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - app
      - consul
    depends_on:
      - registrator
      - consul
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - registrator

  consul:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap ui"


  registrator:
     image: gliderlabs/registrator:latest
     command: "-internal consul://consul:8500"
     container_name: registrator
     links:
       - "consul"
     depends_on:
        - consul
     volumes:
        - /var/run/docker.sock:/tmp/docker.sock

